;CHANGE THESE VALUE IF YOU WANT TO UPDATE YOUR SETTINGS FROM HERE
;BUT DO NOT CHANGE THE PARAMETERS NAME

[Smtp]
Email = None
Password = None
Destination = None
Server = None
Port = 587

[Settings]
Password = None
Api_Key = None
Proxy_List = Proxies/Proxy_list.txt
Show_Logs = False
Path = None
